services:
  - type: web
    name: backend
    runtime: docker
    dockerfilePath: ./server-python/Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: database
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
  - type: static
    name: client
    buildCommand: "npm install && npm run build"
    staticPublishPath: ./dist/public
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
  - type: psql
    name: database
    plan: free
